### ISSUE TITLE
KeyError while trying to simulate events

### ISSUE THREAD

**Issue by JuventoP** [fewagner/cait#7]
I wanted to simulate some absorber/carrier events to understand the pulse shapes and features. When I try to run the following code, I get a KeyError "Unable to open object (object 'fit_coefficients' doesn't exist)". The function dh.simulate_pulses() is what throws the error. However, it turns out that I have to calculate and fit the standard event before simulating by running dh.calc_sev.  The full code (fixed) is given below.

```
import cait as ai
import numpy as np
import matplotlib.pyplot as plt
%config InlineBackend.figure_formats = ['svg']

path_data = './'
fname = 'test_001'
channels_rdt = [0,1]
channels_h5 = [0,1]

dh = ai.DataHandler(channels=channels_rdt)
dh.set_filepath(path_h5=path_data,
                fname=fname,
                appendix=False)

decay_time = dh.get('events','decay_time')[0]
absorbers = ai.cuts.LogicalCut(initial_condition=decay_time > 4)
carriers = ai.cuts.LogicalCut(absorbers.get_antiflag())

dh.apply_array_fit(processes=4, truncation_level=[2, 1], first_channel_dominant=True)

dh.calc_sev(t0_start=None,
            opt_start=False,
            use_idx=absorbers.get_idx(),
            memsafe=True)

dh.simulate_pulses(path_sim='absorbers_001.h5',
                   size_events=500,
                   size_noise=0,
                   ev_ph_intervals=[[0, 3], [0, 3]],
                   t0_interval=[-20, 20],
                   rms_thresholds=[1, 1],
                   assign_labels=[1],
                   fake_noise=True)

dh.calc_sev(t0_start=None,
            opt_start=False,
            use_idx=carriers.get_idx(),
            memsafe=True)

dh.simulate_pulses(path_sim='carriers_001.h5',
                   size_events=500,  
                   name_appendix='_carrier',
                   channels_exceptional_sev=[0],
                   ev_ph_intervals=[[0, 3], [0, 3]],
                   t0_interval=[-20, 20],
                   rms_thresholds=[1, 1],
                   assign_labels=[8],
                   fake_noise=True,
                  )
```

**Comment by fewagner** [comment]
Hey Praveen! :-)
I think I know whats going on there. For the simulation, we use the fitted pulse shape parameters from the standard event of the measured data contained in the HDF5 file to which the DataHandler points. So you need to calculate the standard event first, before you can simulate events. When calculating the standard event with the dedicated "dh.calc_sev" method, this also automatically fits the pulse shape model and stores the parameters in the HDF5 file. 

Could you check if that solves the problem? 

If so, you could also try to add a more descriptive error message in the Cait code, and push to a new branch :)

**Comment by JuventoP** [comment]
Hey Felix,

Thanks for your reply, I was able to simulate some events. However,
for convenience I had to reinstall the CAIT package but when I do that
I get the error message "note: This error originates from a
subprocess, and is likely not a problem with pip. ERROR: Failed
building wheel for numpy ERROR: Could not build wheels for numpy,
which is required to install pyproject.toml-based projects". Although
I'm sure there is a problem with the way I install CAIT, could you
help me fix the issue? I would like to talk to you regarding this and
some other questions that I have. We can meet at your convenience.

Thank you
Best regards,
Praveen Murali

**Comment by fewagner** [comment]
Hi Praveen,
This looks like an issue with Numpy, not Cait. I quickly googled it and it seems to be a known issue, likely from a version incompatibility, e.g. discussed here ([ERROR: Could not build wheels for numpy,
which is required to install pyproject.toml-based projects](https://stackoverflow.com/questions/70565965/error-failed-building-wheel-for-numpy-error-could-not-build-wheels-for-numpy)). Maybe you want to check your Python environment and that you have all the right packages and versions installed. I don't think I can help you with that. 
Also, let's keep debugging questions in the issue tracker (or even better in the Discourse, once you have a CERN account: [here](https://cryocluster-discourse.web.cern.ch/)).

**Comment by JuventoP** [comment]
Hey Felix,

Thanks for the reply. I'll check if the numpy and python versions are
compatible. Moreover, we can discuss on Discourse once I get my CERN
account.

Best,
Praveen
